version: "3.9"

networks:
  frankslab-uk:
    external: true

services:
  geo-server:
    build:
      context: .
      dockerfile: Containerfile
    container_name: geo-server
    restart: unless-stopped
    environment:
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
    volumes:
      - geo-server-data:/data
    networks:
      - frankslab-uk

volumes:
  geo-server-data:
